version: "3.3"
services:
  prosody:
    container_name: prosody
    image: prosody/prosody
    volumes:
      - "./data/prosody/config:/etc/prosody:ro"
    ports:
      - "5222:5222"
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - prosody
    stdin_open: true # docker run -i
    tty: true # docker run -t
